server:
  port: 8082
spring:
  application:
    name: BooKLibraryService
  datasource:
    url: jdbc:mysql://localhost:3306/rebirth?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 2222
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: rebirth
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true